// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  image: dynamic(() => import("./Image")),
  link: dynamic(() => import("./Link")),
  section: dynamic(() => import("./Content")),
  subtitle: dynamic(() => import("./Subtitle")),
};
